Repository fuchicorp/isitup, pull requests merged in 2020-06, with the labels that each got.

#17 Added all people domains.
  configurations/domains.yaml
Labels: DevOps Feature, Grafana, Helm, Jenkins, Prometheus

#18 Dev feature/team2
  deployments/terraform/isitup.tf
  deployments/terraform/variables.tf
Labels: Bash Scripting, DevOps Feature

#26 Fixed stage environment
  deployments/terraform/variables.tf
Labels: DevOps Feature, DevOps Release
